#!/bin/sh

echo "Executing git/hooks/post-commit"

VERSION_FOLDER=version
VERSION_FILE=version/version.go
CURRENT_VERSION=$(git describe --always --long --dirty)
CURRENT_VERSION_DATE=$(date)

function generateVersionFile () {
    mkdir -p $VERSION_FOLDER
	rm -f $VERSION_FILE
	echo "// Code generated by git post-commit hook; DO NOT EDIT." >> $VERSION_FILE
	echo "package version" >> $VERSION_FILE
	echo "const Hash = \"$CURRENT_VERSION\"" >> $VERSION_FILE
	echo "const Date = \"$CURRENT_VERSION_DATE\"" >> $VERSION_FILE
}

echo
if [ -a .commit ]; then
    rm .commit
    generateVersionFile
    git add $VERSION_FOLDER
    git commit --amend -C HEAD --no-verify
fi

